export const levelOptions = [
  { label: "N5", value: "N5" },
  { label: "N4", value: "N4" },
  { label: "N3", value: "N3" },
  { label: "N2", value: "N2" },
  { label: "N1", value: "N1" },
  { label: "UNKNOW", value: "UNKNOW" },
]

export const typeWordsOptions = [
  { label: "Verb - Group 1", value: "Verb - Group 1" },
  { label: "Verb - Group 2", value: "Verb - Group 2" },
  { label: "Verb - Group 3", value: "Verb - Group 3" },
  { label: "Noun", value: "Noun" },
  { label: "Adjective - i", value: "Adjective - i" },
  { label: "Adjective - na", value: "Adjective - na" },
  { label: "Adverb", value: "Adverb" },
  { label: "Pronoun", value: "Pronoun" },
  { label: "Preposition", value: "Preposition" },
  { label: "Conjunction", value: "Conjunction" },
  { label: "Interjection", value: "Interjection" },
  { label: "Phrase", value: "Phrase" },
  { label: "Expression", value: "Expression" },
  { label: "Counter", value: "Counter" },
  { label: "Number", value: "Number" },
  { label: "Prefix", value: "Prefix" },
  { label: "Suffix", value: "Suffix" },
  { label: "Particle", value: "Particle" },
  { label: "Auxiliary verb", value: "Auxiliary verb" },
  { label: "Honorific", value: "Honorific" },
  { label: "Onomatopoeia", value: "Onomatopoeia" },
  { label: "Proverb", value: "Proverb" },
  { label: "Other", value: "Other" },
  { label: "Unknown", value: "Unknown" },
]
