# Generated by Django 4.2.3 on 2023-07-27 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grammar",
            options={"ordering": ("grammar",), "verbose_name_plural": "id"},
        ),
    ]
