# Generated by Django 4.2.3 on 2023-07-27 00:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_grammar_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grammar",
            options={"ordering": ("id",), "verbose_name_plural": "grammars"},
        ),
    ]
