# Generated by Django 4.2.3 on 2023-08-12 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0013_rename_criado_por_category_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=20)),
                ("reading", models.CharField(max_length=20, unique=True)),
                ("meaning", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Verbo - Grupo 1", "Verbo - Grupo 1 "),
                            ("Verbo - Grupo 2 ", "Verbo - Grupo 2"),
                            ("Verbo - Grupo 3", "Verbo - Grupo 3"),
                            ("Adjetivo-I", "Adjetivo-I"),
                            ("Adjetivo-NA", "Adjetivo-NA"),
                            ("Substantivo", "Substantivo"),
                            ("Onomatopeia", "Onomatopeia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("N5", "N5"),
                            ("N4", "N4"),
                            ("N3", "N3"),
                            ("N2", "N2"),
                            ("N1", "N1"),
                            ("UNKNOW", "UNKNOW"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "word",
                "verbose_name_plural": "words",
                "ordering": ("word",),
            },
        ),
    ]
