# Generated by Django 4.2.3 on 2023-12-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_text_textwriting_texttranslate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentence",
            name="sentence",
            field=models.CharField(max_length=200),
        ),
    ]
