# Generated by Django 4.2.3 on 2024-01-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_remove_example_reading"),
    ]

    operations = [
        migrations.AddField(
            model_name="conjugation",
            name="causative_passive",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
